version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    env_file: ".env"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "3G"
    restart: always    
