version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./volume:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "2G"
    restart: always    
